services:
  postgres:
    image: postgres:16-alpine
    container_name: bff-place-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bff-place
      POSTGRES_PASSWORD: BffPlace@26
      POSTGRES_DB: core
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: